# Generated by scripts/homebrew-formula.sh in edkadigital/cli for v0.4.0.
class Edka < Formula
  desc "Deploy, diagnose and manage Kubernetes clusters on Edka"
  homepage "https://edka.io/docs/cli/overview/"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.4.0/edka_v0.4.0_darwin_arm64.tar.gz"
      sha256 "6e18d1e1e9ecb823e45b08cfd3dd7971678a102d4c20086a47451d6b1294e8b2"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.4.0/edka_v0.4.0_darwin_amd64.tar.gz"
      sha256 "9be56c6228746b49785c24dbecefe367cc1a75292bcc3da1a2d7e83dc5d3949b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.4.0/edka_v0.4.0_linux_arm64.tar.gz"
      sha256 "4b7483ed8d80820bc80424a923b1eda44901bf9bccd77607a4b8fbe49c9e80dd"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.4.0/edka_v0.4.0_linux_amd64.tar.gz"
      sha256 "d7463439076a2056775ffeffd1d71dbef8e5f611e6b919b0c55af6c028b82fbb"
    end
  end

  def install
    bin.install "edka"
    generate_completions_from_executable(bin/"edka", "completion")
  end

  test do
    assert_match "edka v#{version}", shell_output("#{bin}/edka version")
  end
end
