# Generated by scripts/homebrew-formula.sh in edkadigital/cli for v0.5.0.
class Edka < Formula
  desc "Deploy, diagnose and manage Kubernetes clusters on Edka"
  homepage "https://edka.io/docs/cli/overview/"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.5.0/edka_v0.5.0_darwin_arm64.tar.gz"
      sha256 "c47452f3ae79221a4abf99339d5b5858c6c898fd2209bdd1e6dde4110b635622"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.5.0/edka_v0.5.0_darwin_amd64.tar.gz"
      sha256 "a28277ceb148889b99462044e76f183ffe93c8dc3dfa182aff1b6cf4afdee908"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.5.0/edka_v0.5.0_linux_arm64.tar.gz"
      sha256 "3ab8e6605660361ea9b546e1ecc09323aea14feacdc1ec726c424520ebfdec7e"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.5.0/edka_v0.5.0_linux_amd64.tar.gz"
      sha256 "d848f2b7da73b30a0197a4cd2f76fb8620b6d9bc37dca6bf309decf0b9c8a034"
    end
  end

  def install
    bin.install "edka"
    generate_completions_from_executable(bin/"edka", "completion")
  end

  test do
    assert_match "edka v#{version}", shell_output("#{bin}/edka version")
  end
end
