# Generated by scripts/homebrew-formula.sh in edkadigital/cli for v0.3.0.
class Edka < Formula
  desc "Deploy, diagnose and manage Kubernetes clusters on Edka"
  homepage "https://edka.io/docs/cli/overview/"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.3.0/edka_v0.3.0_darwin_arm64.tar.gz"
      sha256 "52ea6c38d8acf97e0ba58e350d11d213604ef041a1b40a97aa453c91ae583ee7"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.3.0/edka_v0.3.0_darwin_amd64.tar.gz"
      sha256 "4ca9921aef40d817ccd1419ccb66ce7e48cb44c170de8ee309b540f21e6bab80"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/edkadigital/cli/releases/download/v0.3.0/edka_v0.3.0_linux_arm64.tar.gz"
      sha256 "cc886d25367d4c0941c6fe7048b1fcec229b91c6e2bd2ed301b6c96581e23b1e"
    end
    on_intel do
      url "https://github.com/edkadigital/cli/releases/download/v0.3.0/edka_v0.3.0_linux_amd64.tar.gz"
      sha256 "44810af300996b5361650640ff3385e14ba9a531e708b93dbcac0bcc706660f1"
    end
  end

  def install
    bin.install "edka"
    generate_completions_from_executable(bin/"edka", "completion")
  end

  test do
    assert_match "edka v#{version}", shell_output("#{bin}/edka version")
  end
end
